### ISSUE TITLE
plot(t,v) is much slower than plot(t.data(), v.data())

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#78]

**Comment by edovanveen** [comment]
Probably linked to #79

**Comment by tkuenzmw** [comment]
I also add my 2 cents about plot performance. High-level functions like plot and plot3 create a graphics object each time they are called and that is expensive. A cool trick to plot 3d-lines that can change color is to "abuse" the patch primitive.

This has good performance because only one object will be created by the patch function
```
t = linspace(0,2*pi,100);
x = cos(t);
y = sin(t);
z = t;
c = cos(t).^2;
 
colormap(hsv)
patch(x,y,z,c,'FaceColor','none','EdgeColor','interp')
colorbar
view(3)
```
